### ISSUE TITLE
Feature Request: Toggle setting between map units and pixels

### ISSUE THREAD

**Issue by Fair-Strides** [kandashi/map-coords#2]
I figured I could use this module for help with scene coordinates when setting up visual effects and spawning in tokens. I wasn't sure when I saw that it was counting grid squares, and I know I can convert that in my head, but I was wondering:

Is it possible to add a toggle setting to see whether it shows up as-is or uses the grid size to count pixels? Could probably put the pixels on the grid intersections if that'd be easier than giving the centers of each square.

Thanks for reading!

**Comment by kandashi** [comment]
Im afraid this is a bit off-scope
