### ISSUE TITLE
Coordinates display state is not respected on canvas refresh

### ISSUE THREAD

**Issue by RogueEntityX** [kandashi/map-coords#3]
Core 0.242
DnD5e 1.5.6
Map Coordinates 0.1.02 (Compatibility Risk (9.2))

When performing a refresh of the canvas (F5), it does not respect the coordinate display state. If I set it (using the toggle button in the Measurement Controls tool) to show border and individual grid labels, or turn off ALL labels, after a refresh, it reverts to displaying the border labels only state.

Also, as a request, would it be possible to add the display status as a dropdown selection to the "Grid" tab of the scene configuration, thus allowing the display state to be scene specific?

**Comment by kandashi** [comment]
Fraid no on both accounts. Both would be wonky and time consuming to implement for minimal functionality
