### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ggagnon76** [kandashi/map-coords#4]
Thanks for this module.  I've been using it for a Play by Post game, grabbing screenshots to keep the players updated.  It's been great so far, but I finally ran into a situation where it doesn't work quite right...

I have a very big map, and I only want to use a portion of it, around the middle right side of the map.  I can't find a way to move the coordinates to be at a tight enough zoom level to include them without making my tokens tiny.

I tried to offset the map itself so the area I need is in the top left corner of the scene, but your map coordinates are tied to the background image, and not the scene.  So that didn't help.

I tried the offset option, but the offset applies to both X and Y.  If I get X just right, the Y coordinates are nowhere useful.

My feature request is: the ability to grab the top left anchor where the coordinates start, and drop it where I want it on the map.

**Comment by kandashi** [comment]
There is an option to display coords on each map square not at the top/left of the map
